stages:
  - build
  - deploy  # dummy stage to follow the template guidelines
  
build-job:
    stage: build
    tags:
        - aeur01
    script:
        - echo "Compiling the code..."
        - echo "Compile comlete"

deploy-job:
    stage: deploy
    tags:
        - aeur01
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed"